language: python
python:
  - "3.6"
services:
  - postgresql
  - xvfb
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
install:
  - pip install -r solr-admin-app/requirements/dev.txt
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
  - psql -c 'create database namex;' -U postgres
  - export SOLR_ADMIN_APP_DATABASE_NAME=namex
  - export SOLR_ADMIN_APP_DATABASE_USERNAME=postgres
script:
  - pytest solr-admin-app/tests
